### ISSUE TITLE
OurStory-About

### ISSUE THREAD

**Issue by ladycodeer** [Recoded-Spark-Turkey-2022/The-Incredibles#25]

**Comment by chiturca** [comment]
---
name: About Container/Story Chlid Component💡
about: adding styling and the main structure of the page without functionality
labels: enhancement
---

## Summary

Starting with the second page of the App. "About container component" will be added and then "our story" part will be added into it. Again, we are starting with the main structuring and styling for the issue. Functionality will be added later on.

### Screenshots
![Folder Hierarchy](https://user-images.githubusercontent.com/113294105/209548967-bc3993ac-18ef-4b0c-b04f-7e970fa0cc36.png)

![Story Page](https://user-images.githubusercontent.com/113294105/209548987-19e9b107-061f-4783-b7df-534db09c1c9b.png)
