### ISSUE TITLE
OurTeam-About

### ISSUE THREAD

**Issue by ladycodeer** [Recoded-Spark-Turkey-2022/The-Incredibles#26]

**Comment by chiturca** [comment]
---
name: Team Component/AboutPage💡
about: adding styling and the main structure of the page without functionality
labels: enhancement
---

## Summary

"Our team" component will be added into AboutPage. Again, we are starting with the main structuring and styling for the issue. Functionality will be added later on.

### Screenshots

![Team](https://user-images.githubusercontent.com/113294105/209720459-7e2f3897-9aa0-4b53-b1cd-3e068493555b.png)


### Constriants / Details

Tailwind will be used.
