### ISSUE TITLE
User-Profile

### ISSUE THREAD

**Issue by ladycodeer** [Recoded-Spark-Turkey-2022/The-Incredibles#43]

**Comment by chiturca** [comment]
---
name: UserProfile Page 💡
about: Adding UserProfile folder and related components
labels: enhancement
---

## Summary

Add UserProfile folder and specify the components could be used here. 

### Screenshots

![UserProfile](https://user-images.githubusercontent.com/113294105/210236749-ae31987f-7090-4d3f-996a-60d9d21813ff.png)


### Constriants / Details

- Idle user can not reach this page directly. 
- User should be logged in.
- Connection to main page might be with Home button in this page's Navbar.
